/**
 * Textes FR pour le niveau `thirdMandate` (guerre de Succession d’Espagne).
 */
export const messagesFrThirdMandate = {
  "level.successionWar.name": "Soleil couchant, couronne vacante",
  "level.successionWar.introTitle": "1701 — Au soleil déclinant : testaments, couronnes et longue guerre",
  "level.successionWar.introBody":
    "Avec la mort de Charles II sans héritier, l’arbre des Habsbourg espagnols s’éteint et toute l’Europe recompose la carte. De Castille aux Pays-Bas méridionaux, de Naples aux routes de l’argent américain, le « trône d’Espagne » n’est pas seulement une couronne : c’est un faisceau de ressources impériales et maritimes. Au cœur du parti bourbon se trouve Philippe, duc d’Anjou—petit-fils de Louis XIV (fils du Grand Dauphin Louis)—qui régnerait en Espagne sous le nom de Philippe V s’il montait sur le trône. Versailles invoque ce lien de grand-père à petit-fils, de longues alliances matrimoniales bourbonnes et le testament du défunt ; Vienne et la Cour impériale invoquent la continuité habsbourgeoise et la peur d’un cernement bourbon. Londres et La Haye, jalouses de la Manche et du commerce, se rangent à des coalitions qui doivent contenir Versailles sans sacrifier leurs propires empires marchands.\n\nCe qui s’ensuit tient moins d’une guerre unique que d’un réseau mobile de fronts : places fortes et négociateurs dans les Pays-Bas espagnols, passages alpins entre Piémont et Rhin, principautés rhénanes écrasées entre armées françaises et impériales, et arithmétique navale des colonies. Les traités d’Utrecht tenteront de fixer durablement la carte ; ce chapitre est la longue traction où la monarchie française étire tribut, fiscalité et prestige sous l’envie des autres couronnes.",
  "level.successionWar.ending.victory":
    "Quand les canons cèdent aux clauses, la France n’obtient pas une carte sans coût — mais elle préserve la continuité dynastique et l’appareil d’État. Dans une guerre d’usure, finir en restant gouvernable est déjà une victoire durement acquise.\n\nReculez du parchemin, et le règne de Louis XIV projette une ombre plus longue qu’un seul traité. Il a consolidé une monarchie exceptionnellement centralisée : armées permanentes, intendants, chorégraphie de Versailles — autant de leviers qui ont fait rentrer nobles et provinces dans une machine administrative et de cour obéissante au trône. Cette machine projetait la puissance et la peur : des guerres de Dévolution à la Ligue d’Augsbourg puis à la guerre de Neuf Ans, les voisins ont appris un réflexe — contenir la France avant qu’elle ne devienne la seule voix du concert européen. La splendeur tenait un livre : des décennies d’ambition ont habitué le Trésor à l’emprunt, aux offices vénaux et aux expédients de guerre, si bien que la Succession d’Espagne n’était que la facture rendue au comptant. La politique religieuse noue le même récit : la révocation de l’édit de Nantes a serré l’unité catholique au prix d’exils, de soupçons et de plaies confessionnelles que la diplomatie ne pouvait effacer. La guerre de Succession était l’ardoise de ce système ; en sortir avec une couronne encore crédible, c’est autant une question d’institutions, de mémoire et de récit que de frontières.",
  "level.successionWar.ending.victoryByTier.bourbon":
    "Au palier bourbon, le bilan des traités vous est favorable : Madrid reste dans l’orbite dynastique bourbonienne, et Versailles peut convertir l’usure de guerre en gain politique défendable, malgré les garde-fous anti-union.\n\nPourtant l’héritage du Roi-Soleil n’est pas seulement une clause avantageuse. La centralisation lui survit : les mêmes nerfs administratifs qui déplaçaient régiments et tailles ont dressé l’Europe à surveiller toute primauté française. La tension fiscale ne disparaît pas avec le silence des canons : elle se reporte sur les intérêts, les offices et l’habitude d’emprunter encore. Le règlement confessionnel du règne — unité catholique payée par l’exclusion huguenote — continue de colorer la lecture des capitales protestantes. Votre victoire fixe le titre ; les notes de bas de page parlent d’entretien, de méfiance et du prix différé de la gloire.",
  "level.successionWar.ending.victoryByTier.compromise":
    "Compromis conforme à l’axe historique : Utrecht–Rastatt–Baden ne consacre pas un hégémon unique. Philippe V reste à Madrid, tandis que renonciations, réajustements frontaliers et clauses maritimes-commerciales verrouillent le risque d’union franco-espagnole. Votre fin n’est pas une domination, mais un équilibre signé et exécutoire.\n\nCe compromis est aussi une épitaphe sur le monde de Louis XIV. Sa vie a soudé monarchie absolue et mobilisation permanente : un centre plus fort, un continent plus jaloux, et un moteur fiscal capable d’éblouir Versailles tout en gémissant dans les livres. Les coalitions avaient appris à parler d’une seule voix contre l’outrance française ; Utrecht a gravé ce vocabulaire dans le droit. À l’intérieur du royaume, la politique religieuse — unité imposée, minorités poussées hors du cadre — a laissé des rancœurs qu’aucun traité ne blanchit. Le compromis que vous tenez est donc doublement historique : il clôt la guerre de Succession et avoue qu’aucune couronne, si brillante soit-elle, ne pouvait refaire l’Europe sans payer en garde-fous, soupçons et dette reportée.",
  "level.successionWar.ending.victoryByTier.habsburg":
    "Au palier favorable aux Habsbourg, vous gagnez surtout en évitant le pire : la France conserve une place, mais sous des contraintes accrues sur frontières, mers et latitude dynastique. Le titre dit victoire ; les clauses racontent le coût.\n\nCe coût se lit à la lumière de tout un règne. Louis XIV a laissé un État capable de commander provinces et élites comme peu de prédécesseurs, mais il a aussi enseigné aux rivaux à coordonner leurs flottes, leurs subsides et leurs arguments juridiques contre la prépondérance française. La machine fiscale qui a nourri ses guerres a survécu à sa splendeur, laissant ministres et intendants face aux offices vendus, aux intérêts dus et aux contribuables qui avaient appris la résistance autant que l’obéissance. La politique confessionnelle aiguisait le tableau : rigueur catholique à la maison, exil huguenot à l’étranger — autant d’éléments qui ont nourri la volonté protestante de financer encore un tour de contention. À ce palier, votre épilogue est lucide : la France demeure grande, mais sous la géométrie méfiante que d’autres ont dessinée pendant que le Roi-Soleil arpentait encore la galerie des Glaces.",
  "level.successionWar.ending.victoryWarDevolutionExtra":
    "La guerre de Dévolution hante encore la façon dont les cabinets « cotent » l’initiative française : les voisins se souviennent des premières poussées bourboniennes et tissent leurs alliances en conséquence. Une diplomatie disciplinée plus tard limite la spirale — mais la réputation, comme la dette, se capitalise d’un règne à l’autre.",
  "level.successionWar.ending.defeat":
    "Vous n’avez pas transformé la guerre de succession en ordre durable : trésor, légitimité et conduite de l’État se défont ensemble. À la dernière ligne, la France perd plus que des positions — elle perd la crédibilité d’un pouvoir encore capable de stabiliser l’Europe.",
  "level.successionWar.ending.victorySuccessionTrackCap":
    "Le combat des couronnes s’achève dans l’éclat : le droit bourbon et la grandeur française, forgés dans les testaments, l’acier et la plume des ambassades, s’imposent comme un triomphe sans réplique. Philippe d’Anjou à Madrid n’est plus un pari mais une proclamation portée par le soleil — jalousies et ligues, de la Manche à la Méditerranée, s’inclinent devant votre marche de victoire. C’est l’heure du Roi-Soleil au zénith : l’héritage d’Espagne et le diadème bourbon ne font plus qu’un, et l’histoire retiendra ce jour en lettres d’or.\n\nMême à ce zénith, la vie derrière le triomphe murmure ses conditions. La centralisation a donné à la France une voix incontournable ; elle a aussi dressé l’Europe à s’organiser contre cette voix. Les finances de siège et le faste de cour laissent un Trésor qui continuera de se réveiller face aux intérêts quand les trompettes se tairont. Les choix confessionnels du règne — unité catholique, exil huguenot — survivent dans la défiance diplomatique autant que dans la prière. Vous avez gagné la carte de l’ambition ; la gouverner est la guerre plus lente qui dépasse tout monarque.",
  "level.successionWar.ending.defeatSuccessionTrackFloor":
    "Au plancher de la piste, l’initiative a changé de mains : argumentaire viennois, pression financière et maritime de La Haye et de Londres, et sécurité impériale convergent en grammaire commune défavorable à Versailles. La France peut encore plaider ; elle n’écrit plus le règlement. Cette défaite est territoriale, mais aussi narrative.",

  "event.successionCrisis.name": "Crise de succession",
  "event.successionCrisis.desc":
    "À la mort de Charles II sans héritier, la ligne des Habsbourg espagnols s’éteint : l’Europe doit rattacher ce grand composite — cœurs castillan et aragonais, satellites italiens, Pays-Bas méridionaux, argent américain — à un successeur crédible. Versailles revendique l’héritage pour Philippe d’Anjou en invoquant des alliances de longue date et le testament du défunt, tout en promettant aux cours voisines de ne pas fusionner immédiatement les deux monarchies. Vienne et la branche autrichienne des Habsbourg plaident droits féminins, partages anciens et crainte d’une mainmise française sur la Méditerranée occidentale et les routes coloniales ; elles charrient alliances impériales et coalitions maritimes. Chaque camp aligne juristes et généalogistes pour prouver son titre, et la guerre de papier préfigure la guerre de cabinets et de campagnes.\n\nPayez 3 Fonds pour affirmer une prétention Bourbon plus forte (+1 sur la piste), ou refusez et commencez à −1. Si ignoré jusqu’en fin d’année, compte comme refus (−1) et l’adversaire Habsbourg apparaît quand même.",
  "event.opponentHabsburg.name": "Adversaire : camp des Habsbourg",
  "event.opponentHabsburg.desc":
    "De Vienne aux juristes de Madrid, catholiques convaincus et pragmatiques du Saint-Empire tissent une contre-légitimité aux prétentions bourbonnes—textes, prestige impérial et peur du encadrement français. Cette ligne représente chaque année la pression diplomatique et militaire de ce camp ; la main adverse symbolise les moyens de pression encore disponibles.",
  "event.utrechtTreaty.name": "Négociations d’Utrecht",
  "event.utrechtTreaty.desc":
    "Contexte : à partir de 1713, la Grande Alliance négocie avec la France et l’Espagne bourbonienne à Utrecht, Rastatt, Baden et La Haye pour clore la guerre de Succession d’Espagne. Les traités maintiennent Philippe V à Madrid tout en excluant une union dynastique franco-espagnole ; échanges territoriaux, droits commerciaux et clauses coloniales redessinent une carte que les cours peuvent défendre.\n\nLe bouton ci-dessous met fin immédiatement à la guerre de succession (clôture par traités). À la signature, la piste de succession actuelle fige l’épilogue ; la ligne adverse continue jusqu’à résolution. Si vous ne signez pas tout de suite, chaque fin d’année consomme un tour de la fenêtre de négociation (6 au premier affichage ; il en reste {n}). À 0, la guerre prend fin automatiquement comme si vous signiez maintenant.",
  "log.utrechtPeaceSettlement.title":
    "Tour {turn} : {event} — fin des hostilités par traités ; la crise de succession est close. La piste est gelée et ne bouge plus via événements ni cartes.",
  "log.utrechtPeaceSettlement.body.bourbon":
    "À la signature votre lecture bourbonienne domine déjà (piste ≥ +5) : les clauses penchent vers « Philippe V demeure à Madrid, territoires échangés et garde-fous empêchent l’union des deux couronnes. » Les récits classiques alignent Sicile, Pays-Bas espagnols, Gibraltar et asientos américains ; dans ce palier l’encre adverse cède davantage — Madrid bourbonien se défend plus aisément à Versailles, tandis que les notes de bas de page rappellent l’appétit cartographique jadis prêté au Roi-Soleil.",
  "log.utrechtPeaceSettlement.body.compromise":
    "Trame historique : entre 1713 et 1715 Utrecht, Rastatt et Baden transportent la guerre de Succession d’Espagne des cantonnements vers le parchemin. L’Europe accepte l’Espagne et l’Amérique de Philippe V tout en imposant renonciations, bans dynastiques et articles commerciaux qui excluent la fusion des deux monarchies ; Londres prend Gibraltar et des parts du commerce de transport, la Savoie bascule vers la Sicile, les Provinces-Unies et le Reich achètent des garanties douanières, militaires et rhénanes exécutoires. L’équilibre n’est pas un slogan mais un calendrier de frontières, de bureaux de douane et d’escortes — ce à quoi s’accroche l’épilogue utrechtois « amical » du chapitre : ni carte bourbonienne maximale, ni expulsion grand-alliée de Madrid.",
  "log.utrechtPeaceSettlement.body.habsburg":
    "À la signature la pression coalitionniste est basse (piste ≤ −5) : les traités achètent surtout la sécurité de Vienne et de la Grande Alliance, pas un triomphe français. Compensations piémontaises et rhénanes, réajustements des Pays-Bas et langage de tutelle autour d’un Madrid bourbonien se cumulent ; Philippe peut rester, mais garanties périphériques, concessions coloniales et freins commerciaux vont plus loin — une paix sur papier comme première étape pour re-cadrer la France, non comme dernier mot.",
  "event.bavarianCourtRealignment.name": "Sondage de basculement bavarois",
  "event.bavarianCourtRealignment.desc":
    "Contexte : pendant la guerre de Succession d’Espagne, l’électeur Maximilien II Emmanuel de Bavière s’allie à Louis XIV et à Philippe V ; prince-évêque électeur de Cologne et acteur du collège des princes-électeurs, il ménage un espace politique aux prétentions bourbonno-espagnoles, tandis que la Grande Alliance et Vienne combinent subsides, sanctions impériales et marchandages d’après-bataille (surtout après Blenheim) pour tenter de ramener Munich vers la coalition. Le long de l’axe Rhin–sud de l’Empire, un hochement de tête à la cour ou en conseil de guerre peut faire pencher la balance sur l’héritage espagnol.\n\nPayez 2 Fonds : piste +1 ; si la ligne habsbourgeoise est active et que la guerre n’est pas finie, l’adversaire pioche immédiatement 1 carte depuis son deck. Si ignoré : piste −1.",
  "event.portugueseTariffNegotiation.name": "Négociation tarifaire portugaise",
  "event.portugueseTariffNegotiation.desc":
    "Contexte : pendant la guerre de Succession d’Espagne, le Portugal se réaligne sur la ligue maritime ; les traités de Methuen (1703) échangent des droits favorables sur les vins contre l’accès des lainages anglais, intégrant la politique douanière lisboète à l’économie de guerre de la Grande Alliance.\n\nPayez un coût en Fonds lié au Trésor : Trésor +1 et piste +1. Si ignoré : aucun bonus.",
  "event.imperialElectorsMood.name": "Humeur des princes-électeurs",
  "event.imperialElectorsMood.desc":
    "Contexte : à mesure que la guerre de Succession d’Espagne s’élargit, le collège des princes-électeurs et la politique du Reichstag comptent au centre du jeu, non en marge. Les trois électeurs ecclésiastiques rhénans et leurs pairs laïcs doivent jongler entre passages de troupes, charges impériales et promesses financières venues de Vienne, Berlin ou Dresde. Après l’élection de Joseph Ier comme roi des Romains, les diètes, mandats et tonalité des débats électoraux fixent jusqu’où le droit impérial peut contester publiquement Philippe Bourbon à Madrid — et quelle marge diplomatique reste à Versailles. La France cherche, dans les formes de l’Empire, à adoucir l’hostilité des électeurs tout en protégeant son prétendant espagnol ; le moindre basculement de leur humeur serre à la fois le récit de succession et votre légitimité intérieure.\n\nPayez 2 Fonds ou Intervention : si la ligne habsbourgeoise est active et que la guerre n’est pas finie, l’adversaire pioche immédiatement 1 carte depuis son deck. Si ignoré : piste −1 et Légitimité −1.",
  "event.localizedSuccessionWar.name": "Combats localisés de succession",
  "event.localizedSuccessionWar.desc":
    "Contexte : la succession espagnole ne se joue pas en une bataille décisive, mais en campagnes qui se superposent — Flandre et Rhin, Italie et confins ibériques — où sièges, incursions et quartiers d’hiver se répètent d’année en année. Payer un nouveau cycle d’engagement ne choisit pas l’issue : cours et armées subissent le sort d’un embrasement local.\n\nPayez 4 Fonds (l’Intervention ne peut pas lever cet événement) : la piste de succession varie de −1, 0, +1 ou +2, chaque issue à 25 %. Si ignoré en fin d’année : piste −1.",
  "event.dualFrontCrisis.name": "Pris entre deux feux",
  "event.dualFrontCrisis.desc":
    "Contexte (1708) : revers français sensibles à la fois dans les Pays-Bas espagnols et en théâtre italien — la Grande Alliance serre les rangs en Flandre et au Piémont, et les lignes de ravitaillement tendent à rompre quand l’effort doit se partager entre deux fronts. À Versailles, on hésite entre relâcher la pression sur un front pour consolider l’autre, ou monter en charge au prix d’un surcoût fiscal et politique.\n\nQuel que soit le choix, la pression effective du camp habsbourgeois augmente (budget adverse +1). **Céder provisoirement :** piste −3. **Élargir la guerre :** piste +1, légitimité −1, +3 Charges fiscales mélangées au deck. Si ignoré en fin d’année : piste −3 et budget adverse +1.",
  "event.louisXivLegacy1715.name": "L’héritage de Louis XIV",
  "event.louisXivLegacy1715.desc":
    "Contexte (1715) : Louis XIV meurt, et la plus longue mise en scène de la monarchie absolue s’achève dans la fatigue des comptes et des cérémonies ; le couchant du Roi-Soleil ne met pas fin à la pression, il en change la forme. Versailles conserve des rouages administratifs puissants, mais usés par des décennies de guerre et de dépense de cour ; autour d’un roi mineur, ministres, régents, officiers et grands corps testent la vraie chaîne d’autorité. L’État peut encore gouverner, mais chaque décision est prise sous dette politique et financière. Cette année charnière vous force à choisir non pas entre stabilité et coût, mais entre deux manières de payer le prix de la transition.\n\n**Régence de garde :** Pouvoir −1, Légitimité −1, ajoutez 1 Fardeau fiscal à votre pioche. **Gouvernement direct du jeune roi :** Pouvoir +1, ajoutez 3 Fardeaux fiscaux, et gagnez le statut permanent Doute de minorité. Si non résolu en fin d’année, l’événement est traité comme Régence de garde.",

  "card.bourbonMarriageProclamation.name": "Proclamation du mariage bourbon",
  "card.bourbonMarriageProclamation.background": "Narratif dynastique",
  "card.bourbonMarriageProclamation.desc":
    "Contexte : alliances bourbonniennes et droit successoral servent de récit public pour affirmer la légitimité de la branche d’Anjou sur le trône espagnol et réduire l’espace de manœuvre habsbourgeois.\n\nPouvoir +1. Piste de succession +1. Gagnez Sérénité de l'alliance dynastique pendant 2 tours (+1 carte conservée en fin d'année).",
  "card.grandAllianceInfiltrationDiplomacy.name": "Diplomatie d’infiltration de la Grande Alliance",
  "card.grandAllianceInfiltrationDiplomacy.background": "Diviser la coalition",
  "card.grandAllianceInfiltrationDiplomacy.desc":
    "Contexte : cours neutres, comptoirs et réseaux d’information alourdissent la coordination des ligues anti-françaises, si bien que la Grande Alliance ne transpose pas systématiquement toute sa pression sur la succession espagnole.\n\nPiste de succession +1. Pioche 1. Ce tour, coût adverse −1 (min 0).",
  "card.italianTheaterTroopRedeploy.name": "Redéploiement théâtre italien",
  "card.italianTheaterTroopRedeploy.background": "Front alpin",
  "card.italianTheaterTroopRedeploy.desc":
    "Contexte : manœuvres et combats en Piémont, à Milan et à Naples transforment les gains de campagne en appui concret aux prétentions bourbonnes—mais le trésor saigne pour l’axe alpin et le Pô.\n\nPiste de succession +2. Ajoute 1 Fardeau fiscal au deck.",
  "card.usurpationEdict.name": "Édit d’usurpation",
  "card.usurpationEdict.background": "Rituel brisé",
  "card.usurpationEdict.desc":
    "Contexte : imposer une reconnaissance par un langage de succession hors protocole peut faire gagner du terrain narratif à court terme, mais entame le crédit dynastique à l’intérieur comme à l’extérieur.\n\nPiste de succession +2. Pioche 1. Gagne Crise de légitimité pendant 2 tours (fin de chaque tour : Légitimité -1).",
  "card.habsburgImperialLegitimacyNote.name": "Note de légitimité impériale",
  "card.habsburgImperialLegitimacyNote.background": "Pression juridique",
  "card.habsburgImperialLegitimacyNote.desc":
    "Coût adverse 1. Immédiat : piste de succession −1, puis les Habsbourg piochent immédiatement 1 carte depuis leur deck.",
  "card.habsburgImperialLegitimacyNote.opponentHistory":
    "Les juristes impériaux contestent la légitimité bourbonienne par notes et mémoires, et prolongent la pression légale. En jeu : piste −1, et les Habsbourg piochent immédiatement 1 carte.",
  "card.habsburgLowCountriesAgitation.name": "Agitation dans les Pays-Bas",
  "card.habsburgLowCountriesAgitation.background": "Front du Nord-Ouest",
  "card.habsburgLowCountriesAgitation.desc": "Coût adverse 2. Immédiat : piste −1, Pouvoir −1, Légitimité −1.",
  "card.habsburgLowCountriesAgitation.opponentHistory":
    "L’agitation aux Pays-Bas espagnols devient un levier de coalition contre la France. En jeu : piste −1, Pouvoir −1, Légitimité −1.",
  "card.habsburgGrandAllianceLevy.name": "Contribution de la Grande Alliance",
  "card.habsburgGrandAllianceLevy.background": "Caisse de coalition",
  "card.habsburgGrandAllianceLevy.desc":
    "Coût adverse 2. Immédiat : piste de succession −2 ; ajoute 1 Fardeau fiscal à votre pioche à une position aléatoire.",
  "card.habsburgGrandAllianceLevy.opponentHistory":
    "Subsides de coalition, emprunts hollandais et impôts impériaux entretiennent la pression. En jeu : piste de succession −2 et +1 Fardeau fiscal dans votre deck.",
  "card.habsburgImperialCustomsDelay.name": "Retards douaniers impériaux",
  "card.habsburgImperialCustomsDelay.background": "Friction portuaire",
  "card.habsburgImperialCustomsDelay.desc":
    "Coût adverse 2. Immédiat : Trésor −1 et +1 Fardeau fiscal à votre pioche (position aléatoire) ; différé : l’année suivante, tentatives de pioche −1 (minimum 1).",
  "card.habsburgImperialCustomsDelay.opponentHistory":
    "Les retards douaniers étranglent la trésorerie sans bataille décisive. En jeu : Trésor −1, +1 Fardeau fiscal, et tentatives de pioche −1 l’année suivante (min 1).",
  "card.habsburgAngloDutchMaritimeInterdiction.name": "Retenue anglo-hollandaise",
  "card.habsburgAngloDutchMaritimeInterdiction.background": "Saisies en mer et lettres retardées",
  "card.habsburgAngloDutchMaritimeInterdiction.desc":
    "Coût adverse 1. Immédiat : Pouvoir −1 ; différé : l’année suivante, le Financement issu du Trésor au début d’année est réduit de 1 (pas en dessous de 0 au total) et les tentatives de pioche −1 (minimum 1).",
  "card.habsburgAngloDutchMaritimeInterdiction.opponentHistory":
    "Lettres de marque, convois plus serrés et saisies sur la Manche et la mer du Nord retardent lettres de change et caisses : Versailles voit sa liquidité opérationnelle amincie. En jeu : Pouvoir −1, Financement depuis le Trésor l’année suivante −1 (min 0 au total) et tentatives de pioche −1 (min 1).",
  "card.habsburgRhineMagazineEmbargo.name": "Embargo des magasins",
  "card.habsburgRhineMagazineEmbargo.background": "Étranglement logistique",
  "card.habsburgRhineMagazineEmbargo.desc":
    "Coût adverse 1. Immédiat : piste de succession −1 ; différé : l’année suivante, le Financement issu du Trésor au début d’année est réduit de 1 (pas en dessous de 0 au total).",
  "card.habsburgRhineMagazineEmbargo.opponentHistory":
    "Cercles impériaux et princes riverains ralentissent poudre, fourrage et affrètements de bacs : interdits « provisoires », péages et saisies grippe l’arrière-front rhénan. En jeu : Financement depuis le Trésor l’année suivante −1 (min 0 au total), et piste de succession −1.",
} as const;
