export {
  buildLevel2StateFromDraft,
  createContinuityLevel2Draft,
  createStandaloneLevel2Draft,
  LEVEL2_CONTINUITY_MAX_REMOVALS,
  LEVEL2_FIXED_NEW_IDS,
  SUNKING_CH1_ID,
  SUNKING_CH2_ID,
  toggleContinuityCardRemoval,
  validateLevel2ContinuityRefit,
  validateLevel2Draft,
  type Level2CarryoverCard,
  type Level2ContinuityDraft,
  type Level2StandaloneDraft,
  type Level2StartDraft,
  type Level2StartMode,
  type Level2Validation,
} from "../levels/sunking/chapter2Transition";
