import type { LevelContent, LevelDef } from "../../data/levelTypes";

export const sunkingFirstMandateDef: LevelDef = {
  id: "firstMandate",
  supportedLocales: ["en", "fr", "zh"],
  nameKey: "level.risingSun.name",
  introTitleKey: "level.risingSun.introTitle",
  introBodyKey: "level.risingSun.introBody",
  ending: {
    victoryBodyKey: "level.risingSun.ending.victory",
    victoryWarDevolutionExtraKey: "level.risingSun.ending.victoryWarDevolutionExtra",
    defeatBodyKey: "level.risingSun.ending.defeat",
  },
  calendarStartYear: 1661,
  yearsPerTurn: 1,
  startingResources: {
    treasuryStat: 2,
    funding: 0,
    power: 2,
    legitimacy: 2,
  },
  standaloneStartingResources: {
    treasuryStat: 2,
    funding: 0,
    power: 2,
    legitimacy: 2,
  },
  winTargets: {
    treasuryStat: 6,
    power: 6,
    legitimacy: 5,
  },
  turnLimitRule: { kind: "fixed", turnLimit: 15 },
  victoryRule: { kind: "resourceTargets" },
  features: {
    europeAlertMechanics: false,
    inflation: { kind: "pressureThreshold", threshold: 12 },
    inflationActivationLogKey: "firstMandateInflationActivated",
  },
  bootstrap: "initial",
  menuBriefKey: "menu.levelBrief.firstMandate",
  targetsUiKey: "ui.targets.firstMandate",
  turnBannerKey: "banner.turn.sunKingAnnual",
  timeStepHintKey: "levelTime.sunKing.oneTurnOneYear",
};

export const sunkingFirstMandateContent: LevelContent = {
  starterDeckTemplateOrder: [
    "funding",
    "funding",
    "funding",
    "funding",
    "crackdown",
    "crackdown",
    "crackdown",
    "reform",
    "reform",
    "ceremony",
    "ceremony",
    "development",
    "development",
  ],
  rollableEventIds: [
    "budgetStrain",
    "publicUnrest",
    "administrativeDelay",
    "tradeOpportunity",
    "politicalGridlock",
    "powerVacuum",
  ],
  slotEscalations: [{ from: "powerVacuum", to: "majorCrisis" }],
  eoyEscalationSchedulers: ["powerVacuum"],
  scriptedCalendarEvents: [
    {
      templateId: "warOfDevolution",
      presenceStartYear: 1667,
      presenceEndYear: 1669,
      overflowSlot: "C",
      attack: {
        fundingCost: 2,
        powerDelta: 1,
        extraTreasuryProbability: 0.5,
        extraTreasuryDelta: 1,
      },
      antiCoalition: {
        drawPenaltyProbability: 0.4,
        drawPenaltyDelta: -1,
        activeYearsAfterAttack: 5,
      },
    },
  ],
  opening: {
    turnOnePrefix: ["tradeOpportunity", "administrativeDelay"],
    standaloneCarryoverIdPrefix: "standalone_old_",
  },
  procedural: {
    firstTurnEmptyBoardCount: 2,
  },
};

export const sunkingSecondMandateDef: LevelDef = {
  id: "secondMandate",
  supportedLocales: ["en", "fr", "zh"],
  nameKey: "level.gloryUnderStrain.name",
  introTitleKey: "level.gloryUnderStrain.introTitle",
  introBodyKey: "level.gloryUnderStrain.introBody",
  ending: {
    victoryBodyKey: "level.gloryUnderStrain.ending.victory",
    victoryWarDevolutionExtraKey: "level.gloryUnderStrain.ending.victoryWarDevolutionExtra",
    defeatBodyKey: "level.gloryUnderStrain.ending.defeat",
  },
  calendarStartYear: 1676,
  yearsPerTurn: 1,
  startingResources: {
    treasuryStat: 3,
    funding: 0,
    power: 3,
    legitimacy: 3,
  },
  standaloneStartingResources: {
    treasuryStat: 7,
    funding: 0,
    power: 7,
    legitimacy: 5,
  },
  winTargets: {
    treasuryStat: 10,
    power: 8,
    legitimacy: 10,
  },
  turnLimitRule: { kind: "calendarEnd", endYear: 1701 },
  victoryRule: {
    kind: "gated",
    earliestCalendarYear: 1696,
    minLegitimacy: 6,
  },
  features: {
    europeAlertMechanics: true,
    inflation: { kind: "always" },
  },
  bootstrap: "chapter2Standalone",
  menuBriefKey: "menu.levelBrief.secondMandate",
  targetsUiKey: "ui.targets.secondMandate",
  turnBannerKey: "banner.turn.sunKingAnnual",
  timeStepHintKey: "levelTime.sunKing.oneTurnOneYear",
};

export const sunkingSecondMandateContent: LevelContent = {
  starterDeckTemplateOrder: [
    "funding",
    "funding",
    "funding",
    "funding",
    "crackdown",
    "crackdown",
    "crackdown",
    "reform",
    "reform",
    "ceremony",
    "ceremony",
    "grainRelief",
    "grainRelief",
    "taxRebalance",
    "taxRebalance",
    "diplomaticCongress",
  ],
  rollableEventIds: [
    "versaillesExpenditure",
    "nobleResentment",
    "provincialNoncompliance",
    "risingGrainPrices",
    "taxResistance",
    "courtScandal",
    "militaryPrestige",
    "commercialExpansion",
    "talentedAdministrator",
    "warWeariness",
    "jesuitPatronage",
  ],
  slotEscalations: [],
  eoyEscalationSchedulers: [],
  scriptedCalendarEvents: [
    {
      templateId: "expansionRemembered",
      presenceStartYear: 1676,
      presenceEndYear: 1677,
      overflowSlot: "D",
      requiresWarOfDevolutionAttacked: true,
    },
    {
      templateId: "cautiousCrown",
      presenceStartYear: 1676,
      presenceEndYear: 1677,
      overflowSlot: "D",
      requiresWarOfDevolutionAttacked: false,
    },
    {
      templateId: "nymwegenSettlement",
      presenceStartYear: 1678,
      presenceEndYear: 1682,
      overflowSlot: "D",
    },
    {
      templateId: "revocationNantes",
      presenceStartYear: 1685,
      presenceEndYear: 1688,
      overflowSlot: "D",
    },
    {
      templateId: "leagueOfAugsburg",
      presenceStartYear: 1686,
      presenceEndYear: 1690,
      overflowSlot: "E",
    },
    {
      templateId: "nineYearsWar",
      presenceStartYear: 1689,
      presenceEndYear: 1697,
      overflowSlot: "E",
    },
    {
      templateId: "ryswickPeace",
      presenceStartYear: 1697,
      presenceEndYear: 1700,
      overflowSlot: "F",
    },
  ],
  opening: {
    turnOnePrefix: [],
    standaloneTurnOnePrefix: ["versaillesExpenditure", "taxResistance"],
    standaloneCarryoverIdPrefix: "standalone_old_",
  },
  procedural: {
    firstTurnStandaloneEmptyBoardMin: 3,
  },
};
