import type { CardTemplate, CardTemplateId } from "../../types/card";
import type { CardTag } from "../../types/tags";

const ROYAL: readonly CardTag[] = ["royal"];
const EXTRA: readonly CardTag[] = ["extra"];
const EXTRA_CONSUME: readonly CardTag[] = ["extra", "consume"];
const INFLATION: readonly CardTag[] = ["inflation"];
const CONSUME: readonly CardTag[] = ["consume"];
const OPPONENT: readonly CardTag[] = ["opponent"];
const SUCCESSION_CONTEST: readonly CardTag[] = ["successionContest"];

export const cardTemplates: Record<CardTemplateId, CardTemplate> = {
  funding: {
    id: "funding",
    cost: 0,
    tags: ROYAL,
    titleKey: "card.funding.name",
    backgroundKey: "card.funding.background",
    descriptionKey: "card.funding.desc",
    effects: [{ kind: "gainFunding", amount: 1 }],
  },
  crackdown: {
    id: "crackdown",
    cost: 1,
    tags: ROYAL,
    titleKey: "card.crackdown.name",
    backgroundKey: "card.crackdown.background",
    descriptionKey: "card.crackdown.desc",
    effects: [],
  },
  diplomaticIntervention: {
    id: "diplomaticIntervention",
    cost: 0,
    tags: EXTRA,
    titleKey: "card.diplomaticIntervention.name",
    backgroundKey: "card.diplomaticIntervention.background",
    descriptionKey: "card.diplomaticIntervention.desc",
    effects: [],
  },
  fiscalBurden: {
    id: "fiscalBurden",
    cost: 2,
    tags: CONSUME,
    titleKey: "card.fiscalBurden.name",
    backgroundKey: "card.fiscalBurden.background",
    descriptionKey: "card.fiscalBurden.desc",
    effects: [],
  },
  antiFrenchContainment: {
    id: "antiFrenchContainment",
    cost: 2,
    tags: CONSUME,
    titleKey: "card.antiFrenchContainment.name",
    backgroundKey: "card.antiFrenchContainment.background",
    descriptionKey: "card.antiFrenchContainment.desc",
    effects: [],
  },
  reform: {
    id: "reform",
    cost: 2,
    tags: INFLATION,
    titleKey: "card.reform.name",
    backgroundKey: "card.reform.background",
    descriptionKey: "card.reform.desc",
    effects: [
      { kind: "modResource", resource: "power", delta: 1 },
      { kind: "drawCards", count: 1 },
    ],
  },
  ceremony: {
    id: "ceremony",
    cost: 2,
    tags: INFLATION,
    titleKey: "card.ceremony.name",
    backgroundKey: "card.ceremony.background",
    descriptionKey: "card.ceremony.desc",
    effects: [{ kind: "modResource", resource: "legitimacy", delta: 1 }],
  },
  development: {
    id: "development",
    cost: 3,
    tags: INFLATION,
    titleKey: "card.development.name",
    backgroundKey: "card.development.background",
    descriptionKey: "card.development.desc",
    effects: [{ kind: "modResource", resource: "treasuryStat", delta: 1 }],
  },
  grainRelief: {
    id: "grainRelief",
    cost: 3,
    tags: INFLATION,
    titleKey: "card.grainRelief.name",
    backgroundKey: "card.grainRelief.background",
    descriptionKey: "card.grainRelief.desc",
    effects: [
      { kind: "addPlayerStatus", templateId: "grainReliefDrawBoost", turns: 1 },
      { kind: "addPlayerStatus", templateId: "grainReliefLegitimacyBoost", turns: 1 },
    ],
  },
  taxRebalance: {
    id: "taxRebalance",
    cost: 2,
    tags: INFLATION,
    titleKey: "card.taxRebalance.name",
    backgroundKey: "card.taxRebalance.background",
    descriptionKey: "card.taxRebalance.desc",
    effects: [
      { kind: "modResource", resource: "treasuryStat", delta: 1 },
      { kind: "addPlayerStatus", templateId: "drawPenalty", turns: 2 },
    ],
  },
  diplomaticCongress: {
    id: "diplomaticCongress",
    cost: 3,
    tags: [],
    titleKey: "card.diplomaticCongress.name",
    backgroundKey: "card.diplomaticCongress.background",
    descriptionKey: "card.diplomaticCongress.desc",
    effects: [{ kind: "modResource", resource: "power", delta: 1 }],
  },
  suppressHuguenots: {
    id: "suppressHuguenots",
    cost: 3,
    tags: EXTRA_CONSUME,
    titleKey: "card.suppressHuguenots.name",
    backgroundKey: "card.suppressHuguenots.background",
    descriptionKey: "card.suppressHuguenots.desc",
    effects: [],
  },
  religiousTensionCard: {
    id: "religiousTensionCard",
    cost: 2,
    tags: EXTRA_CONSUME,
    titleKey: "card.religiousTensionCard.name",
    backgroundKey: "card.religiousTensionCard.background",
    descriptionKey: "card.religiousTensionCard.desc",
    effects: [],
  },
  jansenistReservation: {
    id: "jansenistReservation",
    cost: 2,
    tags: EXTRA_CONSUME,
    titleKey: "card.jansenistReservation.name",
    backgroundKey: "card.jansenistReservation.background",
    descriptionKey: "card.jansenistReservation.desc",
    effects: [],
  },
  jesuitCollege: {
    id: "jesuitCollege",
    cost: 2,
    tags: EXTRA,
    titleKey: "card.jesuitCollege.name",
    backgroundKey: "card.jesuitCollege.background",
    descriptionKey: "card.jesuitCollege.desc",
    effects: [{ kind: "modResource", resource: "legitimacy", delta: 1 }],
  },
  bourbonMarriageProclamation: {
    id: "bourbonMarriageProclamation",
    cost: 3,
    tags: SUCCESSION_CONTEST,
    titleKey: "card.bourbonMarriageProclamation.name",
    backgroundKey: "card.bourbonMarriageProclamation.background",
    descriptionKey: "card.bourbonMarriageProclamation.desc",
    effects: [
      { kind: "modResource", resource: "power", delta: 1 },
      { kind: "modSuccessionTrack", delta: 1 },
    ],
  },
  grandAllianceInfiltrationDiplomacy: {
    id: "grandAllianceInfiltrationDiplomacy",
    cost: 3,
    tags: SUCCESSION_CONTEST,
    titleKey: "card.grandAllianceInfiltrationDiplomacy.name",
    backgroundKey: "card.grandAllianceInfiltrationDiplomacy.background",
    descriptionKey: "card.grandAllianceInfiltrationDiplomacy.desc",
    effects: [
      { kind: "modSuccessionTrack", delta: 1 },
      { kind: "drawCards", count: 1 },
    ],
  },
  italianTheaterTroopRedeploy: {
    id: "italianTheaterTroopRedeploy",
    cost: 3,
    tags: SUCCESSION_CONTEST,
    titleKey: "card.italianTheaterTroopRedeploy.name",
    backgroundKey: "card.italianTheaterTroopRedeploy.background",
    descriptionKey: "card.italianTheaterTroopRedeploy.desc",
    effects: [
      { kind: "modSuccessionTrack", delta: 2 },
      { kind: "addCardsToDeck", templateId: "fiscalBurden", count: 1 },
    ],
  },
  habsburgImperialLegitimacyNote: {
    id: "habsburgImperialLegitimacyNote",
    cost: 0,
    opponentCost: 1,
    tags: OPPONENT,
    titleKey: "card.habsburgImperialLegitimacyNote.name",
    backgroundKey: "card.habsburgImperialLegitimacyNote.background",
    descriptionKey: "card.habsburgImperialLegitimacyNote.desc",
    effects: [],
  },
  habsburgLowCountriesAgitation: {
    id: "habsburgLowCountriesAgitation",
    cost: 0,
    opponentCost: 2,
    tags: OPPONENT,
    titleKey: "card.habsburgLowCountriesAgitation.name",
    backgroundKey: "card.habsburgLowCountriesAgitation.background",
    descriptionKey: "card.habsburgLowCountriesAgitation.desc",
    effects: [],
  },
  habsburgGrandAllianceLevy: {
    id: "habsburgGrandAllianceLevy",
    cost: 0,
    opponentCost: 2,
    tags: OPPONENT,
    titleKey: "card.habsburgGrandAllianceLevy.name",
    backgroundKey: "card.habsburgGrandAllianceLevy.background",
    descriptionKey: "card.habsburgGrandAllianceLevy.desc",
    effects: [],
  },
  habsburgImperialCustomsDelay: {
    id: "habsburgImperialCustomsDelay",
    cost: 0,
    opponentCost: 2,
    tags: OPPONENT,
    titleKey: "card.habsburgImperialCustomsDelay.name",
    backgroundKey: "card.habsburgImperialCustomsDelay.background",
    descriptionKey: "card.habsburgImperialCustomsDelay.desc",
    effects: [],
  },
};
