import type { StatusTemplate, StatusTemplateId } from "../../types/status";

export const statusTemplates: Record<StatusTemplateId, StatusTemplate> = {
  powerLeak: {
    id: "powerLeak",
    kind: "drawAttemptsDelta",
    delta: -1,
    titleKey: "status.powerLeak.name",
    historyKey: "status.powerLeak.history",
    descKey: "status.powerLeak.desc",
  },
  drawPenalty: {
    id: "drawPenalty",
    kind: "drawAttemptsDelta",
    delta: -1,
    titleKey: "status.drawPenalty.name",
    historyKey: "status.drawPenalty.history",
    descKey: "status.drawPenalty.desc",
  },
  retentionBoost: {
    id: "retentionBoost",
    kind: "retentionCapacityDelta",
    delta: 1,
    titleKey: "status.retentionBoost.name",
    historyKey: "status.retentionBoost.history",
    descKey: "status.retentionBoost.desc",
  },
  royalBan: {
    id: "royalBan",
    kind: "blockCardTag",
    blockedTag: "royal",
    titleKey: "status.royalBan.name",
    historyKey: "status.royalBan.history",
    descKey: "status.royalBan.desc",
  },
  grainReliefDrawBoost: {
    id: "grainReliefDrawBoost",
    kind: "drawAttemptsDelta",
    delta: 1,
    titleKey: "status.grainReliefDrawBoost.name",
    historyKey: "status.grainReliefDrawBoost.history",
    descKey: "status.grainReliefDrawBoost.desc",
  },
  grainReliefLegitimacyBoost: {
    id: "grainReliefLegitimacyBoost",
    kind: "beginYearResourceDelta",
    resource: "legitimacy",
    delta: 1,
    titleKey: "status.grainReliefLegitimacyBoost.name",
    historyKey: "status.grainReliefLegitimacyBoost.history",
    descKey: "status.grainReliefLegitimacyBoost.desc",
  },
  religiousTolerance: {
    id: "religiousTolerance",
    kind: "drawAttemptsDelta",
    delta: 0,
    titleKey: "status.religiousTolerance.name",
    historyKey: "status.religiousTolerance.history",
    descKey: "status.religiousTolerance.desc",
  },
  huguenotContainment: {
    id: "huguenotContainment",
    kind: "drawAttemptsDelta",
    delta: 0,
    titleKey: "status.huguenotContainment.name",
    historyKey: "status.huguenotContainment.history",
    descKey: "status.huguenotContainment.hintGeneral",
  },
  antiFrenchSentiment: {
    id: "antiFrenchSentiment",
    kind: "drawAttemptsDelta",
    delta: 0,
    titleKey: "status.antiFrenchSentiment.name",
    historyKey: "status.antiFrenchSentiment.history",
    descKey: "status.antiFrenchSentiment.detail",
  },
  greatPowerEncirclement: {
    id: "greatPowerEncirclement",
    kind: "drawAttemptsDelta",
    delta: 0,
    titleKey: "status.greatPowerEncirclement.name",
    historyKey: "status.greatPowerEncirclement.history",
    descKey: "status.greatPowerEncirclement.desc",
  },
  legitimacyCrisis: {
    id: "legitimacyCrisis",
    kind: "drawAttemptsDelta",
    delta: 0,
    titleKey: "status.legitimacyCrisis.name",
    historyKey: "status.legitimacyCrisis.history",
    descKey: "status.legitimacyCrisis.desc",
  },
  minorRegencyDoubt: {
    id: "minorRegencyDoubt",
    kind: "drawAttemptsDelta",
    delta: -1,
    titleKey: "status.minorRegencyDoubt.name",
    historyKey: "status.minorRegencyDoubt.history",
    descKey: "status.minorRegencyDoubt.desc",
  },
  diplomaticCongressDrawBoost: {
    id: "diplomaticCongressDrawBoost",
    kind: "drawAttemptsDelta",
    delta: 1,
    titleKey: "status.diplomaticCongressDrawBoost.name",
    historyKey: "status.diplomaticCongressDrawBoost.history",
    descKey: "status.diplomaticCongressDrawBoost.desc",
  },
  grandAllianceInfiltration: {
    id: "grandAllianceInfiltration",
    kind: "drawAttemptsDelta",
    delta: 0,
    titleKey: "status.grandAllianceInfiltration.name",
    historyKey: "status.grandAllianceInfiltration.history",
    descKey: "status.grandAllianceInfiltration.desc",
  },
  edictBacklog: {
    id: "edictBacklog",
    kind: "drawAttemptsDelta",
    delta: -1,
    titleKey: "status.edictBacklog.name",
    historyKey: "status.edictBacklog.history",
    descKey: "status.edictBacklog.desc",
  },
  provincialFootDragging: {
    id: "provincialFootDragging",
    kind: "drawAttemptsDelta",
    delta: -1,
    titleKey: "status.provincialFootDragging.name",
    historyKey: "status.provincialFootDragging.history",
    descKey: "status.provincialFootDragging.desc",
  },
  nobleGrudge: {
    id: "nobleGrudge",
    kind: "drawAttemptsDelta",
    delta: -1,
    titleKey: "status.nobleGrudge.name",
    historyKey: "status.nobleGrudge.history",
    descKey: "status.nobleGrudge.desc",
  },
  warExhaustion: {
    id: "warExhaustion",
    kind: "drawAttemptsDelta",
    delta: -1,
    titleKey: "status.warExhaustion.name",
    historyKey: "status.warExhaustion.history",
    descKey: "status.warExhaustion.desc",
  },
  frontierWatch: {
    id: "frontierWatch",
    kind: "drawAttemptsDelta",
    delta: -1,
    titleKey: "status.frontierWatch.name",
    historyKey: "status.frontierWatch.history",
    descKey: "status.frontierWatch.desc",
  },
  seaLaneDisarray: {
    id: "seaLaneDisarray",
    kind: "drawAttemptsDelta",
    delta: -1,
    titleKey: "status.seaLaneDisarray.name",
    historyKey: "status.seaLaneDisarray.history",
    descKey: "status.seaLaneDisarray.desc",
  },
  embargoPressure: {
    id: "embargoPressure",
    kind: "drawAttemptsDelta",
    delta: -1,
    titleKey: "status.embargoPressure.name",
    historyKey: "status.embargoPressure.history",
    descKey: "status.embargoPressure.desc",
  },
  confessionalDeadlock: {
    id: "confessionalDeadlock",
    kind: "drawAttemptsDelta",
    delta: -1,
    titleKey: "status.confessionalDeadlock.name",
    historyKey: "status.confessionalDeadlock.history",
    descKey: "status.confessionalDeadlock.desc",
  },
  supplyLineSqueeze: {
    id: "supplyLineSqueeze",
    kind: "beginYearFundingIncomeDelta",
    delta: -1,
    titleKey: "status.supplyLineSqueeze.name",
    historyKey: "status.supplyLineSqueeze.history",
    descKey: "status.supplyLineSqueeze.desc",
  },
  usurpationMobilization: {
    id: "usurpationMobilization",
    kind: "drawAttemptsDelta",
    delta: 1,
    titleKey: "status.usurpationMobilization.name",
    historyKey: "status.usurpationMobilization.history",
    descKey: "status.usurpationMobilization.desc",
  },
  bourbonMarriageRetention: {
    id: "bourbonMarriageRetention",
    kind: "handCapDelta",
    delta: 1,
    titleKey: "status.bourbonMarriageRetention.name",
    historyKey: "status.bourbonMarriageRetention.history",
    descKey: "status.bourbonMarriageRetention.desc",
  },
};
