import type { StatusTemplate, StatusTemplateId } from "../../types/status";

export const statusTemplates: Record<StatusTemplateId, StatusTemplate> = {
  powerLeak: {
    id: "powerLeak",
    kind: "drawAttemptsDelta",
    delta: -1,
    titleKey: "status.powerLeak.name",
    historyKey: "status.powerLeak.history",
    descKey: "status.powerLeak.desc",
  },
  drawPenalty: {
    id: "drawPenalty",
    kind: "drawAttemptsDelta",
    delta: -1,
    titleKey: "status.drawPenalty.name",
    historyKey: "status.drawPenalty.history",
    descKey: "status.drawPenalty.desc",
  },
  retentionBoost: {
    id: "retentionBoost",
    kind: "retentionCapacityDelta",
    delta: 1,
    titleKey: "status.retentionBoost.name",
    historyKey: "status.retentionBoost.history",
    descKey: "status.retentionBoost.desc",
  },
  royalBan: {
    id: "royalBan",
    kind: "blockCardTag",
    blockedTag: "royal",
    titleKey: "status.royalBan.name",
    historyKey: "status.royalBan.history",
    descKey: "status.royalBan.desc",
  },
  grainReliefDrawBoost: {
    id: "grainReliefDrawBoost",
    kind: "drawAttemptsDelta",
    delta: 1,
    titleKey: "status.grainReliefDrawBoost.name",
    historyKey: "status.grainReliefDrawBoost.history",
    descKey: "status.grainReliefDrawBoost.desc",
  },
  grainReliefLegitimacyBoost: {
    id: "grainReliefLegitimacyBoost",
    kind: "beginYearResourceDelta",
    resource: "legitimacy",
    delta: 1,
    titleKey: "status.grainReliefLegitimacyBoost.name",
    historyKey: "status.grainReliefLegitimacyBoost.history",
    descKey: "status.grainReliefLegitimacyBoost.desc",
  },
  religiousTolerance: {
    id: "religiousTolerance",
    kind: "drawAttemptsDelta",
    delta: 0,
    titleKey: "status.religiousTolerance.name",
    historyKey: "status.religiousTolerance.history",
    descKey: "status.religiousTolerance.desc",
  },
  huguenotContainment: {
    id: "huguenotContainment",
    kind: "drawAttemptsDelta",
    delta: 0,
    titleKey: "status.huguenotContainment.name",
    historyKey: "status.huguenotContainment.history",
    descKey: "status.huguenotContainment.hintGeneral",
  },
  antiFrenchSentiment: {
    id: "antiFrenchSentiment",
    kind: "drawAttemptsDelta",
    delta: 0,
    titleKey: "status.antiFrenchSentiment.name",
    historyKey: "status.antiFrenchSentiment.history",
    descKey: "status.antiFrenchSentiment.detail",
  },
  greatPowerEncirclement: {
    id: "greatPowerEncirclement",
    kind: "drawAttemptsDelta",
    delta: 0,
    titleKey: "status.greatPowerEncirclement.name",
    historyKey: "status.greatPowerEncirclement.history",
    descKey: "status.greatPowerEncirclement.desc",
  },
  legitimacyCrisis: {
    id: "legitimacyCrisis",
    kind: "drawAttemptsDelta",
    delta: 0,
    titleKey: "status.legitimacyCrisis.name",
    historyKey: "status.legitimacyCrisis.history",
    descKey: "status.legitimacyCrisis.desc",
  },
  minorRegencyDoubt: {
    id: "minorRegencyDoubt",
    kind: "drawAttemptsDelta",
    delta: -1,
    titleKey: "status.minorRegencyDoubt.name",
    historyKey: "status.minorRegencyDoubt.history",
    descKey: "status.minorRegencyDoubt.desc",
  },
  diplomaticCongressDrawBoost: {
    id: "diplomaticCongressDrawBoost",
    kind: "drawAttemptsDelta",
    delta: 1,
    titleKey: "status.diplomaticCongressDrawBoost.name",
    historyKey: "status.diplomaticCongressDrawBoost.history",
    descKey: "status.diplomaticCongressDrawBoost.desc",
  },
  grandAllianceInfiltration: {
    id: "grandAllianceInfiltration",
    kind: "drawAttemptsDelta",
    delta: 0,
    titleKey: "status.grandAllianceInfiltration.name",
    historyKey: "status.grandAllianceInfiltration.history",
    descKey: "status.grandAllianceInfiltration.desc",
  },
  bourbonMarriageRetention: {
    id: "bourbonMarriageRetention",
    kind: "handCapDelta",
    delta: 1,
    titleKey: "status.bourbonMarriageRetention.name",
    historyKey: "status.bourbonMarriageRetention.history",
    descKey: "status.bourbonMarriageRetention.desc",
  },
};
